ORG 100h

.MODEL SMALL

.STACK 100h ;RESERVA 256 BYTES

.DATA
    mensaje1 DB "Ingresa una palabra: $"
    mensaje2 DB 10,13,"Palabra ivertida: $"

.CODE

MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    ;MOSTRAR MENSAJE DE ENTRADA
    MOV AH,09h
    LEA DX, mensaje1
    INT 21h
    
    ;INICIALIZAR EL CONTADOR
    MOV CX,0
    
LEER_CARACTER:
    MOV AH,01h ;FUNCION PARA LEER CARACTER DEL TECLADO
    INT 21h
    CMP AL,13 ;COMPARADOR SI EL CARACTER ES 13 OSEA ENTER
    JE IMPRIMIR_INVERSO ;JE SALTO EXTERNO A LA FUNCION INDICADA
    PUSH AX ;GUARDA CARACTER EN LA PILA
    INC CX 
    JMP LEER_CARACTER ;SALTA AL INICIO DE LA FUNCION

IMPRIMIR_INVERSO:
    MOV AH,09h
    LEA DX,mensaje2
    INT 21h

;VAMOS A EXTRAER LOS DATOS DE LA PILA
IMPRIMIR:
    POP DX
    MOV AH,02h ;FUNCION DE IMPRESION DE UN CARACTER
    INT 21h
    LOOP IMPRIMIR ;REPETIR CX VECES 
    
    ;FINALIZAR PROGRAMA Y REGRESA AL SO
    MOV AH,4Ch
    INT 21H
    
MAIN ENDP
END MAIN
    
    
    
    
    
    